midefa/midefa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy

from theglue.views import ProjectList, ProjectDetail, ProjectFetchBoards, ProjectLinkBoard, ProjectFetchLists, ProjectFetchAllCards, ProjectFetchLabels

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'midefa.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^project/(?P<pk>\d+)/link/(?P<board>\d+)/$', ProjectLinkBoard.as_view(), name='project_link_board',),
    url(r'^project/(?P<pk>\d+)/fetch/boards$', ProjectFetchBoards.as_view(), name='project_fetch_boards',),
    url(r'^project/(?P<pk>\d+)/fetch/lists$', ProjectFetchLists.as_view(), name='project_fetch_lists',),
    url(r'^project/(?P<pk>\d+)/fetch/labels$', ProjectFetchLabels.as_view(), name='project_fetch_labels',),
    url(r'^project/(?P<pk>\d+)/fetch/all-cards$', ProjectFetchAllCards.as_view(), name='project_fetch_all_cards',),
    url(r'^project/(?P<pk>\d+)/$', ProjectDetail.as_view(), name='project_detail',),
    url(r'^projects/$', ProjectList.as_view(), name='projects',),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': reverse_lazy('login')}, name='logout'),
    url(r'^admin/', include(admin.site.urls)),
)

midefa/theglue/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from midefa.settings import TIME_ZONE
import datetime
from pytz import timezone


class Project(models.Model):
    NONE = 'none'
    VCS = 'vcs'
    SPRINT = 'sprint'
    REQUIREMENT = 'requirement'
    BLOCKING = 'blocking'
    LABEL_USAGE_CHOICES = (
        (VCS, _('VCS')),
        (SPRINT, _('Sprint planning meeting')),
        (REQUIREMENT, _('Need requirements')),
        (BLOCKING, _('Blocking!')),
        (NONE, _('None')),
    )
    name = models.CharField(verbose_name=_("name"), max_length=50, help_text=_("The project's name"))
    trello_api_key = models.CharField(verbose_name=_("trello's api key"), max_length=200, help_text=_("The Trello developer API key"))
    trello_api_secret = models.CharField(verbose_name=_("trello's secret key"), max_length=200, help_text=_("The Trello secret key"))
    trello_token = models.CharField(verbose_name=_("trello's user token"), max_length=200, help_text=_("The Trello token for the authorized user"))
    trello_user = models.CharField(verbose_name=_("trello's user"), max_length=50, help_text=_("The Trello authorized user"))
    board = models.OneToOneField('TrelloBoard', verbose_name=_('board'), blank=True, null=True, help_text=_("The Trello board used in this project"))
    sprint_name = models.CharField(verbose_name=_("sprint name"), max_length=50, help_text=_("String used to concatenate the sprint name"))
    sprint_counter = models.IntegerField(verbose_name=_("sprint counter"), default=0, help_text=_("The counter used to increment sprint number"))
    label_purple = models.CharField(verbose_name=_("purple label name"), max_length=100, blank=True, help_text=_("The name of the purple label"))
    label_green = models.CharField(verbose_name=_("green label name"), max_length=100, blank=True, help_text=_("The name of the green label"))
    label_orange = models.CharField(verbose_name=_("orange label name"), max_length=100, blank=True, help_text=_("The name of the orange label"))
    label_red = models.CharField(verbose_name=_("red label name"), max_length=100, blank=True, help_text=_("The name of the red label"))
    label_blue = models.CharField(verbose_name=_("blue label name"), max_length=100, blank=True, help_text=_("The name of the blue label"))
    label_yellow = models.CharField(verbose_name=_("yellow label name"), max_length=100, blank=True, help_text=_("The name of the yellow label"))
    label_purple_usage = models.CharField(verbose_name=_("purple label usage"), max_length=50, choices=LABEL_USAGE_CHOICES, default=NONE, help_text=_("The usage of the purple label"))
    label_green_usage = models.CharField(verbose_name=_("green label usage"), max_length=50, choices=LABEL_USAGE_CHOICES, default=NONE, help_text=_("The usage of the green label"))
    label_orange_usage = models.CharField(verbose_name=_("orange label usage"), max_length=50, choices=LABEL_USAGE_CHOICES, default=NONE, help_text=_("The usage of the orange label"))
    label_red_usage = models.CharField(verbose_name=_("red label usage"), max_length=50, choices=LABEL_USAGE_CHOICES, default=NONE, help_text=_("The usage of the red label"))
    label_blue_usage = models.CharField(verbose_name=_("blue label usage"), max_length=50, choices=LABEL_USAGE_CHOICES, default=NONE, help_text=_("The usage of the blue label"))
    label_yellow_usage = models.CharField(verbose_name=_("yellow label usage"), max_length=50, choices=LABEL_USAGE_CHOICES, default=NONE, help_text=_("The usage of the yellow label"))

    class Meta:
        verbose_name = _('midefa project')
        verbose_name_plural = _('midefa projects')
        ordering = ['name']

    def __str__(self):
        return "%s" % (self.name,)


class TrelloBoard(models.Model):
    project_origin = models.ForeignKey('Project', verbose_name=_('project'), related_name=_('boards'), help_text=_("Project the board belongs to"))
    board_id = models.CharField(verbose_name=_("board id"), max_length=100, help_text=_("The Trello board id"))
    name = models.CharField(verbose_name=_("name"), max_length=100, help_text=_("The Trello board name"))
    short_url = models.URLField(verbose_name=_("short url"), max_length=200, blank=True, null=True, help_text=_("The Trello board short url"))
    closed = models.BooleanField(verbose_name=_("closed"), default=False, help_text=_("The status of the Trello board"))

    class Meta:
        verbose_name = _('Trello board')
        verbose_name_plural = _('Trello boards')
        ordering = ['name']

    def __str__(self):
        return "%s" % (self.name,)


class TrelloList(models.Model):
    trello_board = models.ForeignKey('TrelloBoard', verbose_name=_('board'), related_name=_('lists'), help_text=_("Board the list belongs to"))
    list_id = models.CharField(verbose_name=_("list id"), primary_key=True, max_length=100, help_text=_("The Trello list id"))
    name = models.CharField(verbose_name=_("name"), max_length=100, help_text=_("The Trello list name"))
    closed = models.BooleanField(verbose_name=_("closed"), default=False, help_text=_("The status of the Trello list"))
    pos = models.IntegerField(verbose_name=_("position"), default=0, help_text=_("The position of the Trello list"))
    watch = models.BooleanField(verbose_name=_("watch"), default=False, help_text=_("Watch for card updates in this list"))

    class Meta:
        verbose_name = _('Trello list')
        verbose_name_plural = _('Trello lists')
        ordering = ['pos']

    def __str__(self):
        return "%s/%s" % (self.trello_board.name, self.name,)


class TrelloCard(models.Model):
    trello_list = models.ForeignKey('TrelloList', verbose_name=_('list'), related_name=_('cards'), help_text=_("List the card belongs to"))
    card_id = models.CharField(verbose_name=_("card id"), primary_key=True, max_length=100, help_text=_("The Trello card id"))
    description = models.TextField(verbose_name=_("description"), blank=True, help_text=_("The Trello card description"))
    id_short = models.IntegerField(verbose_name=_("short id"), default=0, max_length=8, help_text=_("The Trello card short id"))
    name = models.CharField(verbose_name=_("name"), max_length=100, help_text=_("The Trello card name"))
    short_url = models.URLField(verbose_name=_("short url"), max_length=200, blank=True, null=True, help_text=_("The Trello card short url"))
    label_green = models.BooleanField(verbose_name=_("green label"), default=False, help_text=_("The usage of the green label on this card"))
    label_yellow = models.BooleanField(verbose_name=_("yellow label"), default=False, help_text=_("The usage of the yellow label on this card"))
    label_orange = models.BooleanField(verbose_name=_("orange label"), default=False, help_text=_("The usage of the orange label on this card"))
    label_red = models.BooleanField(verbose_name=_("red label"), default=False, help_text=_("The usage of the red label on this card"))
    label_purple = models.BooleanField(verbose_name=_("purple label"), default=False, help_text=_("The usage of the purple label on this card"))
    label_blue = models.BooleanField(verbose_name=_("blue label"), default=False, help_text=_("The usage of the blue label on this card"))
    last_activity = models.DateTimeField(verbose_name=_("last activity"), auto_now_add=True, help_text=_("Timestamp of the last change on Trello"))

    class Meta:
        verbose_name = _('Trello card')
        verbose_name_plural = _('Trello cards')
        ordering = ['id_short']

    def recent_status(self):
        """Returns True if the last activity is less than 7 days old."""
        if self.last_activity > datetime.datetime.now(timezone(TIME_ZONE))-datetime.timedelta(days=4):
            return True
        else:
            return False

    def __str__(self):
        return "[#%s] %s" % (self.id_short, self.name,)


class TrelloMember(models.Model):
    member_id = models.CharField(verbose_name=_("member id"), primary_key=True, max_length=100, help_text=_("The Trello member id"))
    full_name = models.CharField(verbose_name=_("full name"), max_length=100, help_text=_("The Trello full name"))
    username = models.CharField(verbose_name=_("username"), max_length=100, help_text=_("The Trello username"))

    class Meta:
        verbose_name = _('Trello member')
        verbose_name_plural = _('Trello members')
        ordering = ['full_name']

    def __str__(self):
        return "%s" % (self.full_name,)


class TrelloCheckList(models.Model):
    trello_card = models.ForeignKey('TrelloCard', verbose_name=_('card'), related_name=_('check lists'), help_text=_("Card the check list belongs to"))
    check_list_id = models.CharField(verbose_name=_("check list id"), primary_key=True, max_length=100, help_text=_("The Trello check list id"))
    name = models.CharField(verbose_name=_("name"), max_length=100, help_text=_("The Trello check list name"))

    class Meta:
        verbose_name = _('Trello check list')
        verbose_name_plural = _('Trello check lists')
        ordering = ['check_list_id']

    def __str__(self):
        return "[#%s] %s" % (self.trello_card.id_short, self.name,)


class TrelloCheckListItem(models.Model):
    OPEN = 'incomplete'
    CLOSED = 'complete'
    ITEM_STATE_CHOICES = (
        (OPEN, _('Open')),
        (CLOSED, _('Done')),
    )

    trello_check_list = models.ForeignKey('TrelloCheckList', verbose_name=_('check list'), related_name=_('items'), help_text=_("Check list the item belongs to"))
    item_id = models.CharField(verbose_name=_("item id"), primary_key=True, max_length=100, help_text=_("The Trello item id"))
    name = models.CharField(verbose_name=_("name"), max_length=100, help_text=_("The Trello item name"))
    state = models.CharField(verbose_name=_("state"), max_length=20, choices=ITEM_STATE_CHOICES, default=OPEN)

    class Meta:
        verbose_name = _('Trello check list item')
        verbose_name_plural = _('Trello check list items')

midefa/theglue/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView, RedirectView
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from .models import Project, TrelloBoard
from .utils import fetch_boards, fetch_lists, fetch_all_cards, fetch_labels


class ProjectList(ListView):
    model = Project


class ProjectDetail(DetailView):
    model = Project


class ProjectFetchBoards(TemplateView):

    template_name = "theglue/project_fetch_boards.html"

    def get_context_data(self, **kwargs):
        context = super(ProjectFetchBoards, self).get_context_data(**kwargs)
        project = get_object_or_404(Project, pk=kwargs['pk'])
        context['object'] = project
        context['project'] = project
        boards = fetch_boards(project)
        context['object_list'] = boards
        return context


class ProjectFetchLists(RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs['pk'])
        fetch_lists(project)
        return reverse('project_detail', kwargs={'pk': project.id})


class ProjectFetchAllCards(RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs['pk'])
        fetch_all_cards(project)
        return reverse('project_detail', kwargs={'pk': project.id})


class ProjectFetchLabels(RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs['pk'])
        fetch_labels(project)
        return reverse('project_detail', kwargs={'pk': project.id})


class ProjectLinkBoard(RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        project = get_object_or_404(Project, pk=kwargs['pk'])
        board = get_object_or_404(TrelloBoard, pk=kwargs['board'])
        project.board = board
        project.save()
        return reverse('project_detail', kwargs={'pk': project.id})
        #return super(ProjectLinkBoard, self).get_redirect_url(*args, **kwargs)

midefa/templates/theglue/project_detail.html
{% extends "base.html" %}

{% block project %}{{ object.name }} >{% endblock project %}

{% block title %}Project's summary{% endblock title %}

{% block content %}
    <h1>{{ object.name }} project's summary</h1>
    <dl>
        <dt>Project</dt><dd>{{ object.name }}</dd>
        <dt>Trello API</dt><dd>{{ object.trello_api_key }}</dd>
        <dt>Trello username</dt><dd>{{ object.trello_user }}</dd>
        <dt>Board</dt>
        <dd>{% if not object.board %}<a href="{% url 'project_fetch_boards' object.id %}">Fetch boards</a>
            {% else %}{{ object.board }} (<a href="{% url 'project_fetch_boards' object.id %}">change</a>)
            {% endif %}</dd>
        <dt>Next sprint #</dt><dd>{{ object.sprint_name }} {{ object.sprint_counter }}</dd>
        <dt>Labels</dt>
        <dd>
            <table>
                <tr>
                    <th>Label</th><th>Usage</th>
                </tr>
                <tr>
                    <td><span class="label label-green">{% if object.label_green %}{{ object.label_green }}{% else %}no label assigned{% endif %}</span></td><td>{{ object.get_label_green_usage_display }}</td>
                </tr>
                <tr>
                    <td><span class="label label-yellow">{% if object.label_yellow %}{{ object.label_yellow }}{% else %}no label assigned{% endif %}</span></td><td>{{ object.get_label_yellow_usage_display }}</td>
                </tr>
                <tr>
                    <td><span class="label label-orange">{% if object.label_orange %}{{ object.label_orange }}{% else %}no label assigned{% endif %}</span></td><td>{{ object.get_label_orange_usage_display }}</td>
                </tr>
                <tr>
                    <td><span class="label label-red">{% if object.label_red %}{{ object.label_red }}{% else %}no label assigned{% endif %}</span></td><td>{{ object.get_label_red_usage_display }}</td>
                </tr>
                <tr>
                    <td><span class="label label-purple">{% if object.label_purple %}{{ object.label_purple }}{% else %}no label assigned{% endif %}</span></td><td>{{ object.get_label_purple_usage_display }}</td>
                </tr>
                <tr>
                    <td><span class="label label-blue">{% if object.label_blue %}{{ object.label_blue }}{% else %}no label assigned{% endif %}</span></td><td>{{ object.get_label_blue_usage_display }}</td>
                </tr>
            </table>
            <a href="{% url 'project_fetch_labels' object.id %}">Update labels</a>
        </dd>
    </dl>

    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th>List</th>
            <th>Watch</th>
            <th>Usage</th>
        </tr>
        {% for list in object.board.lists.all %}
            {% if list.watch %}
                <tr>
                    <td>{{ list.name }}</td>
                    <td>{{ list.watch }}</td>
                    <td></td>
                </tr>
                {% for card in list.cards.all %}
                    <tr>
                        <td></td>
                        <td colspan="2">
                            {{ card }} {% if card.recent_status %}<span class="label label-hot">HOT</span> {% endif %}
                            {% if card.label_green %}<span class="label label-green">{{ object.label_green }}</span> {% endif %}
                            {% if card.label_yellow %}<span class="label label-yellow">{{ object.label_yellow }}</span> {% endif %}
                            {% if card.label_orange %}<span class="label label-orange">{{ object.label_orange }}</span> {% endif %}
                            {% if card.label_red %}<span class="label label-red">{{ object.label_red }}</span> {% endif %}
                            {% if card.label_purple %}<span class="label label-purple">{{ object.label_purple }}</span> {% endif %}
                            {% if card.label_blue %}<span class="label label-blue">{{ object.label_blue }}</span> {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        {% endfor %}
    </table>

    <ul>
        <li><a href="{% url 'project_fetch_lists' object.id %}">Refresh lists</a></li>
        <li><a href="{% url 'project_fetch_all_cards' object.id %}">Fetch cards</a></li>
    </ul>
{% endblock content %}

midefa/templates/theglue/project_fetch_boards.html
{% extends "base.html" %}

{% block project %}{{ object.name }} >{% endblock project %}

{% block title %}Fetch boards{% endblock title %}

{% block content %}
    <h1>Fetch boards for {{ object.name }}</h1>
    <table>
        <tr>
            <th>Board's name</th>
            <th>Trello ID</th>
            <th>Closed</th>
            <th>Created</th>
            <th></th>
        </tr>
        {% for fetch_board in object_list %}
            <tr>
                <td>{{ fetch_board.board.name }}</td>
                <td>{{ fetch_board.board.board_id }}</td>
                <td>{{ fetch_board.board.closed }}</td>
                <td>{{ fetch_board.created }}</td>
                <td><a href="{% url 'project_link_board' object.id fetch_board.board.id %}">Link</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}

midefa/templates/theglue/project_list.html
{% extends "base.html" %}

{% block title %}Project's list{% endblock title %}

{% block content %}
    <h1>Project's list</h1>
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th>Project's name</th>
            <th>Trello user</th>
        </tr>
        {% for project in object_list %}
            <tr>
                <td><a href="{% url 'project_detail' project.id %}">{{ project.name }}</a></td>
                <td>{{ project.trello_user }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}